// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/dl.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/video/[id].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/dl-island.tsx";
import * as $$2 from "./islands/main.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/dl.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/video/[id].tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/dl-island.tsx": $$1,
    "./islands/main.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
